# Autogenerated file
# 2010 Geoyeob Kim
# As a part of the thesis implementation
from numpy import array, linalg, zeros
from math import sin, cos
from scipy import sparse
from MathUtil import cot

def MassMatrixAndCqdVectorQuat(p, q, pd, qd, I):
    p1, p2, p3 = p
    qw, qx, qy, qz = q
    Ixx, Iyy, Izz, Iww = I

    M = array(zeros((7,7)))
    Cqd = array(zeros(7))

    ################################################
    #      Variable: M
    ################################################
    _x1 = 4*Ixx
    _x2 = 4*Iyy
    _x3 = 4*Izz
    _x4 = _x3+_x2+_x1
    _x5 = pow(qw,2)
    _x6 = _x3+_x2
    _x7 = pow(qx,2)
    _x8 = _x3+_x1
    _x9 = pow(qy,2)
    _x10 = _x2+_x1
    _x11 = pow(qz,2)
    _x12 = _x3-4*Iyy
    _x13 = _x12*qy*qz+4*Ixx*qw*qx
    _x14 = _x1-4*Izz
    _x15 = _x14*qx*qz+4*Iyy*qw*qy
    _x16 = _x2-4*Ixx
    _x17 = 4*Izz*qw*qz+_x16*qx*qy
    _x18 = _x16*qw*qz+4*Izz*qx*qy
    _x19 = 4*Iyy*qx*qz+_x14*qw*qy
    _x20 = 4*Ixx*qy*qz+_x12*qw*qx
    M[  0,  0] = Iww
    M[  1,  1] = Iww
    M[  2,  2] = Iww
    M[  3,  3] = _x10*_x11+_x8*_x9+_x6*_x7+_x4*_x5
    M[  3,  4] = _x13
    M[  3,  5] = _x15
    M[  3,  6] = _x17
    M[  4,  3] = _x13
    M[  4,  4] = _x8*_x11+_x10*_x9+_x4*_x7+_x6*_x5
    M[  4,  5] = _x18
    M[  4,  6] = _x19
    M[  5,  3] = _x15
    M[  5,  4] = _x18
    M[  5,  5] = _x6*_x11+_x4*_x9+_x10*_x7+_x8*_x5
    M[  5,  6] = _x20
    M[  6,  3] = _x17
    M[  6,  4] = _x19
    M[  6,  5] = _x20
    M[  6,  6] = _x4*_x11+_x6*_x9+_x8*_x7+_x10*_x5
    pd1, pd2, pd3 = pd
    qdw, qdx, qdy, qdz = qd
    ################################################
    #      Variable: Cqd
    ################################################
    _x1 = 4*Ixx
    _x2 = 4*Iyy
    _x3 = 4*Izz
    _x4 = _x3+_x2+_x1
    _x5 = pow(qdw,2)
    _x6 = -4*Iyy
    _x7 = -4*Izz
    _x8 = _x7+_x6+_x1
    _x9 = pow(qdx,2)
    _x10 = -4*Ixx
    _x11 = _x7+_x2+_x10
    _x12 = pow(qdy,2)
    _x13 = _x3+_x6+_x10
    _x14 = pow(qdz,2)
    _x15 = 8*Iyy
    _x16 = 8*Izz
    _x17 = _x16+_x15
    _x18 = _x15-8*Izz
    _x19 = _x18*qdy*qdz+_x17*qdw*qdx
    _x20 = 8*Ixx
    _x21 = _x16+_x20
    _x22 = _x16-8*Ixx
    _x23 = _x22*qdx*qdz+_x21*qdw*qdy
    _x24 = _x20-8*Iyy
    _x25 = _x15+_x20
    _x26 = _x25*qdw*qdz+_x24*qdx*qdy
    _x27 = _x24*qdw*qdz+_x25*qdx*qdy
    _x28 = _x21*qdx*qdz+_x22*qdw*qdy
    _x29 = _x17*qdy*qdz+_x18*qdw*qdx
    Cqd[  3] = _x26*qz+_x23*qy+_x19*qx+(_x13*_x14+_x11*_x12+_x8*_x9+_x4*_x5)*qw
    Cqd[  4] = _x28*qz+_x27*qy+(_x11*_x14+_x13*_x12+_x4*_x9+_x8*_x5)*qx+_x19*qw
    Cqd[  5] = _x29*qz+(_x8*_x14+_x4*_x12+_x13*_x9+_x11*_x5)*qy+_x27*qx+_x23*qw
    Cqd[  6] = (_x4*_x14+_x8*_x12+_x11*_x9+_x13*_x5)*qz+_x29*qy+_x28*qx+_x26*qw
    return M, Cqd

