#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Optimization-based rigid body simulator
2010 Geoyeob Kim

Symbolic form of a rigid box dynamics for implicit integration
"""
from numpy import *
from math import pow, sin, cos

def Symbolicf(q, v, qd, F, T, I, m):
	f = zeros((14))

	qw, qx, qy, qz = q
	vx, vy, vz = v
	qdw, qdx, qdy, qdz = qd
	Fx, Fy, Fz = F
	Tx, Ty, Tz = T
	Ixx, Iyy, Izz = I
	
	f[0] = vx;
	f[1] = vy;
	f[2] = vz;
	f[3] = qdw;
	f[4] = qdx;
	f[5] = qdy;
	f[6] = qdz;
	f[7] = Fx/m;
	f[8] = Fy/m;
	f[9] = Fz/m;
	f[10] = (qdw*qdw)*qw-(qdx*qdx)*qw-(qdy*qdy)*qw-(qdz*qdz)*qw-(qy*(Ty-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qz*(Tz+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+qdw*qdx*qx*2.0+qdw*qdy*qy*2.0+qdw*qdz*qz*2.0-(Tx*qx*(1.0/2.0))/Ixx-(Iyy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	f[11] = -(qdw*qdw)*qx+(qdx*qdx)*qx-(qdy*qdy)*qx-(qdz*qdz)*qx-(qz*(Ty-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(qy*(Tz+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+qdw*qdx*qw*2.0+qdx*qdy*qy*2.0+qdx*qdz*qz*2.0+(Tx*qw*(1.0/2.0))/Ixx+(Iyy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	f[12] = -(qdw*qdw)*qy-(qdx*qdx)*qy+(qdy*qdy)*qy-(qdz*qdz)*qy+(qw*(Ty-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qx*(Tz+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+qdw*qdy*qw*2.0+qdx*qdy*qx*2.0+qdy*qdz*qz*2.0+(Tx*qz*(1.0/2.0))/Ixx+(Iyy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	f[13] = -(qdw*qdw)*qz-(qdx*qdx)*qz-(qdy*qdy)*qz+(qdz*qdz)*qz+(qx*(Ty-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(qw*(Tz+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+qdw*qdz*qw*2.0+qdx*qdz*qx*2.0+qdy*qdz*qy*2.0-(Tx*qy*(1.0/2.0))/Ixx-(Iyy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;

	return f

def SymbolicdfdY(q, qd, T, I):
	dfdY = zeros((14,14))
	
	qw, qx, qy, qz = q
	qdw, qdx, qdy, qdz = qd
	Tx, Ty, Tz = T
	Ixx, Iyy, Izz = I
	
	dfdY[0,0] = 0.0;
	dfdY[0,1] = 0.0;
	dfdY[0,2] = 0.0;
	dfdY[0,3] = 0.0;
	dfdY[0,4] = 0.0;
	dfdY[0,5] = 0.0;
	dfdY[0,6] = 0.0;
	dfdY[0,7] = 1.0;
	dfdY[0,8] = 0.0;
	dfdY[0,9] = 0.0;
	dfdY[0,10] = 0.0;
	dfdY[0,11] = 0.0;
	dfdY[0,12] = 0.0;
	dfdY[0,13] = 0.0;
	dfdY[1,0] = 0.0;
	dfdY[1,1] = 0.0;
	dfdY[1,2] = 0.0;
	dfdY[1,3] = 0.0;
	dfdY[1,4] = 0.0;
	dfdY[1,5] = 0.0;
	dfdY[1,6] = 0.0;
	dfdY[1,7] = 0.0;
	dfdY[1,8] = 1.0;
	dfdY[1,9] = 0.0;
	dfdY[1,10] = 0.0;
	dfdY[1,11] = 0.0;
	dfdY[1,12] = 0.0;
	dfdY[1,13] = 0.0;
	dfdY[2,0] = 0.0;
	dfdY[2,1] = 0.0;
	dfdY[2,2] = 0.0;
	dfdY[2,3] = 0.0;
	dfdY[2,4] = 0.0;
	dfdY[2,5] = 0.0;
	dfdY[2,6] = 0.0;
	dfdY[2,7] = 0.0;
	dfdY[2,8] = 0.0;
	dfdY[2,9] = 1.0;
	dfdY[2,10] = 0.0;
	dfdY[2,11] = 0.0;
	dfdY[2,12] = 0.0;
	dfdY[2,13] = 0.0;
	dfdY[3,0] = 0.0;
	dfdY[3,1] = 0.0;
	dfdY[3,2] = 0.0;
	dfdY[3,3] = 0.0;
	dfdY[3,4] = 0.0;
	dfdY[3,5] = 0.0;
	dfdY[3,6] = 0.0;
	dfdY[3,7] = 0.0;
	dfdY[3,8] = 0.0;
	dfdY[3,9] = 0.0;
	dfdY[3,10] = 1.0;
	dfdY[3,11] = 0.0;
	dfdY[3,12] = 0.0;
	dfdY[3,13] = 0.0;
	dfdY[4,0] = 0.0;
	dfdY[4,1] = 0.0;
	dfdY[4,2] = 0.0;
	dfdY[4,3] = 0.0;
	dfdY[4,4] = 0.0;
	dfdY[4,5] = 0.0;
	dfdY[4,6] = 0.0;
	dfdY[4,7] = 0.0;
	dfdY[4,8] = 0.0;
	dfdY[4,9] = 0.0;
	dfdY[4,10] = 0.0;
	dfdY[4,11] = 1.0;
	dfdY[4,12] = 0.0;
	dfdY[4,13] = 0.0;
	dfdY[5,0] = 0.0;
	dfdY[5,1] = 0.0;
	dfdY[5,2] = 0.0;
	dfdY[5,3] = 0.0;
	dfdY[5,4] = 0.0;
	dfdY[5,5] = 0.0;
	dfdY[5,6] = 0.0;
	dfdY[5,7] = 0.0;
	dfdY[5,8] = 0.0;
	dfdY[5,9] = 0.0;
	dfdY[5,10] = 0.0;
	dfdY[5,11] = 0.0;
	dfdY[5,12] = 1.0;
	dfdY[5,13] = 0.0;
	dfdY[6,0] = 0.0;
	dfdY[6,1] = 0.0;
	dfdY[6,2] = 0.0;
	dfdY[6,3] = 0.0;
	dfdY[6,4] = 0.0;
	dfdY[6,5] = 0.0;
	dfdY[6,6] = 0.0;
	dfdY[6,7] = 0.0;
	dfdY[6,8] = 0.0;
	dfdY[6,9] = 0.0;
	dfdY[6,10] = 0.0;
	dfdY[6,11] = 0.0;
	dfdY[6,12] = 0.0;
	dfdY[6,13] = 1.0;
	dfdY[7,0] = 0.0;
	dfdY[7,1] = 0.0;
	dfdY[7,2] = 0.0;
	dfdY[7,3] = 0.0;
	dfdY[7,4] = 0.0;
	dfdY[7,5] = 0.0;
	dfdY[7,6] = 0.0;
	dfdY[7,7] = 0.0;
	dfdY[7,8] = 0.0;
	dfdY[7,9] = 0.0;
	dfdY[7,10] = 0.0;
	dfdY[7,11] = 0.0;
	dfdY[7,12] = 0.0;
	dfdY[7,13] = 0.0;
	dfdY[8,0] = 0.0;
	dfdY[8,1] = 0.0;
	dfdY[8,2] = 0.0;
	dfdY[8,3] = 0.0;
	dfdY[8,4] = 0.0;
	dfdY[8,5] = 0.0;
	dfdY[8,6] = 0.0;
	dfdY[8,7] = 0.0;
	dfdY[8,8] = 0.0;
	dfdY[8,9] = 0.0;
	dfdY[8,10] = 0.0;
	dfdY[8,11] = 0.0;
	dfdY[8,12] = 0.0;
	dfdY[8,13] = 0.0;
	dfdY[9,0] = 0.0;
	dfdY[9,1] = 0.0;
	dfdY[9,2] = 0.0;
	dfdY[9,3] = 0.0;
	dfdY[9,4] = 0.0;
	dfdY[9,5] = 0.0;
	dfdY[9,6] = 0.0;
	dfdY[9,7] = 0.0;
	dfdY[9,8] = 0.0;
	dfdY[9,9] = 0.0;
	dfdY[9,10] = 0.0;
	dfdY[9,11] = 0.0;
	dfdY[9,12] = 0.0;
	dfdY[9,13] = 0.0;
	dfdY[10,0] = 0.0;
	dfdY[10,1] = 0.0;
	dfdY[10,2] = 0.0;
	dfdY[10,3] = qdw*qdw-qdx*qdx-qdy*qdy-qdz*qdz-(qz*(Ixx*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(qy*(Ixx*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qdx*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qdy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdx*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[10,4] = qdw*qdx*2.0-(Tx*(1.0/2.0))/Ixx+(qz*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(qy*(Ixx*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdw*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qdz*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdw*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdz*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[10,5] = qdw*qdy*2.0-(Ty*(1.0/2.0)-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Iyy-(qy*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qz*(Ixx*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(Iyy*qdw*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qdz*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdw*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdz*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[10,6] = qdw*qdz*2.0-(Tz*(1.0/2.0)+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Izz-(qy*(Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qz*(Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(Iyy*qdx*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qdy*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdx*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdy*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[10,7] = 0.0;
	dfdY[10,8] = 0.0;
	dfdY[10,9] = 0.0;
	dfdY[10,10] = qdw*qw*2.0+qdx*qx*2.0+qdy*qy*2.0+qdz*qz*2.0-(qz*(Ixx*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(qy*(Ixx*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*(qx*qx)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*(qx*qx)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[10,11] = qdx*qw*(-2.0)+qdw*qx*2.0-(qz*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(qy*(Ixx*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qw*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qw*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[10,12] = qdy*qw*(-2.0)+qdw*qy*2.0+(qy*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qz*(Ixx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(Iyy*qw*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qw*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[10,13] = qdz*qw*(-2.0)+qdw*qz*2.0+(qy*(Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(qz*(Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(Iyy*(qx*qx)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*(qx*qx)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[11,0] = 0.0;
	dfdY[11,1] = 0.0;
	dfdY[11,2] = 0.0;
	dfdY[11,3] = qdw*qdx*2.0+(Tx*(1.0/2.0))/Ixx+(qy*(Ixx*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(qz*(Ixx*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdx*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdx*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[11,4] = -qdw*qdw+qdx*qdx-qdy*qdy-qdz*qdz-(qy*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(qz*(Ixx*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qdw*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdz*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdw*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdz*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[11,5] = qdx*qdy*2.0+(Tz*(1.0/2.0)+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Izz+(qy*(Ixx*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(qz*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qdw*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qdz*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdw*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdz*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[11,6] = qdx*qdz*2.0-(Ty*(1.0/2.0)-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Iyy+(qy*(Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(qz*(Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qdx*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qdy*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdx*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdy*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[11,7] = 0.0;
	dfdY[11,8] = 0.0;
	dfdY[11,9] = 0.0;
	dfdY[11,10] = qdx*qw*2.0-qdw*qx*2.0+(qy*(Ixx*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(qz*(Ixx*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qw*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qw*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qw*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qw*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[11,11] = qdw*qw*2.0+qdx*qx*2.0+qdy*qy*2.0+qdz*qz*2.0+(qy*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(qz*(Ixx*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*(qw*qw)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*(qw*qw)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qw*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qw*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[11,12] = qdy*qx*(-2.0)+qdx*qy*2.0+(qz*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(qy*(Ixx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(Iyy*(qw*qw)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*(qw*qw)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qw*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qw*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[11,13] = qdz*qx*(-2.0)+qdx*qz*2.0-(qy*(Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(qz*(Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*qw*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qw*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qw*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qw*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[12,0] = 0.0;
	dfdY[12,1] = 0.0;
	dfdY[12,2] = 0.0;
	dfdY[12,3] = qdw*qdy*2.0+(Ty*(1.0/2.0)-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Iyy-(qx*(Ixx*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(qw*(Ixx*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*qdx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[12,4] = qdx*qdy*2.0-(Tz*(1.0/2.0)+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Izz+(qx*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(qw*(Ixx*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qdw*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdz*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdw*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdz*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[12,5] = -qdw*qdw-qdx*qdx+qdy*qdy-qdz*qdz+(qw*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qx*(Ixx*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(Iyy*qdw*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qdz*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdw*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdz*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[12,6] = qdy*qdz*2.0+(Tx*(1.0/2.0))/Ixx+(qw*(Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qx*(Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(Iyy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qdx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qdy*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdy*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[12,7] = 0.0;
	dfdY[12,8] = 0.0;
	dfdY[12,9] = 0.0;
	dfdY[12,10] = qdy*qw*2.0-qdw*qy*2.0-(qx*(Ixx*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(qw*(Ixx*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[12,11] = qdy*qx*2.0-qdx*qy*2.0-(qx*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(qw*(Ixx*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*(qz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*(qz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qw*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qw*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[12,12] = qdw*qw*2.0+qdx*qx*2.0+qdy*qy*2.0+qdz*qz*2.0-(qw*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(qx*(Ixx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(Iyy*(qz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*(qz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qw*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qw*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[12,13] = qdz*qy*(-2.0)+qdy*qz*2.0-(qw*(Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(qx*(Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(Iyy*qx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qy*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qy*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[13,0] = 0.0;
	dfdY[13,1] = 0.0;
	dfdY[13,2] = 0.0;
	dfdY[13,3] = qdw*qdz*2.0+(Tz*(1.0/2.0)+Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0-Iyy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Izz+(qw*(Ixx*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(qx*(Ixx*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qdx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qdy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[13,4] = qdx*qdz*2.0+(Ty*(1.0/2.0)-Ixx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0+Izz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Iyy-(qw*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qdx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(qx*(Ixx*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qdx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*qdw*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qdz*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdw*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qdz*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[13,5] = qdy*qdz*2.0-(Tx*(1.0/2.0))/Ixx+(qw*(Ixx*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qdz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz+(qx*(Ixx*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qdw*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qdz*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdw*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qdz*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[13,6] = -qdw*qdw-qdx*qdx-qdy*qdy+qdz*qdz+(qw*(Ixx*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qdy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qdz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz+(qx*(Ixx*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qdx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Izz*qdz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*qdx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qdy*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qdx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qdy*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[13,7] = 0.0;
	dfdY[13,8] = 0.0;
	dfdY[13,9] = 0.0;
	dfdY[13,10] = qdz*qw*2.0-qdw*qz*2.0+(qw*(Ixx*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qw*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Iyy*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(qx*(Ixx*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qw*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*(qy*qy)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*(qy*qy)*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Iyy*qx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*qx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[13,11] = qdz*qx*2.0-qdx*qz*2.0+(qw*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qx*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(qx*(Ixx*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qx*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0+Izz*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Iyy-(Iyy*qw*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qw*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Iyy*qy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Izz*qy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;
	dfdY[13,12] = qdz*qy*2.0-qdy*qz*2.0-(qx*(Ixx*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qw*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qy*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(qw*(Ixx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0+Ixx*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Iyy*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qz*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0)*(1.0/2.0))/Izz-(Iyy*qw*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qw*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx-(Iyy*qy*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx+(Izz*qy*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx;
	dfdY[13,13] = qdw*qw*2.0+qdx*qx*2.0+qdy*qy*2.0+qdz*qz*2.0-(qw*(Ixx*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Ixx*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0-Iyy*qy*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Iyy*qz*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*4.0)*(1.0/2.0))/Izz-(qx*(Ixx*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0+Ixx*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0-Izz*qx*(qdw*qw+qdx*qx+qdy*qy+qdz*qz)*4.0-Izz*qz*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*4.0)*(1.0/2.0))/Iyy+(Iyy*(qy*qy)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Izz*(qy*qy)*(qdy*qw+qdz*qx-qdw*qy-qdx*qz)*2.0)/Ixx-(Iyy*qx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx+(Izz*qx*qy*(qdx*qw-qdw*qx-qdz*qy+qdy*qz)*2.0)/Ixx;

	return dfdY