/*
 * Autogenerated file
 * 2010 Geoyeob Kim
 * As a part of the thesis implementation
 */
#include "PymPch.h"
#include "macFiberInputVectorDef.h"
void mac_FibDiffW(double fibDiffW[3], const double input[18+18+12]) {
    /***********************************************
     *     Variable: fibDiffW
     ***********************************************/
    double _x1 = -fibbx_ins*qy_ins+fibby_ins*qx_ins+fibbz_ins*qw_ins;
    double _x2 = -fibbx_org*qy_org+fibby_org*qx_org+fibbz_org*qw_org;
    double _x3 = fibbx_ins*qz_ins-fibbz_ins*qx_ins+fibby_ins*qw_ins;
    double _x4 = -fibby_ins*qz_ins+fibbz_ins*qy_ins+fibbx_ins*qw_ins;
    double _x5 = fibbz_ins*qz_ins+fibby_ins*qy_ins+fibbx_ins*qx_ins;
    double _x6 = fibbx_org*qz_org-fibbz_org*qx_org+fibby_org*qw_org;
    double _x7 = -fibby_org*qz_org+fibbz_org*qy_org+fibbx_org*qw_org;
    double _x8 = fibbz_org*qz_org+fibby_org*qy_org+fibbx_org*qx_org;
    fibDiffW[  0] = -qx_org*_x8-qw_org*_x7+qz_org*_x6+qx_ins*_x5+qw_ins*_x4-qz_ins*_x3-qy_org*_x2+qy_ins*_x1-px_org+px_ins;
    fibDiffW[  1] = -qy_org*_x8-qz_org*_x7-qw_org*_x6+qy_ins*_x5+qz_ins*_x4+qw_ins*_x3+qx_org*_x2-qx_ins*_x1-py_org+py_ins;
    fibDiffW[  2] = -qz_org*_x8+qy_org*_x7-qx_org*_x6+qz_ins*_x5-qy_ins*_x4+qx_ins*_x3-qw_org*_x2+qw_ins*_x1-pz_org+pz_ins;
}
