#pragma once

//
// OpenGL Extensions (Win32 only)
// Windows needs to get function pointers from ICD OpenGL drivers,
// because opengl32.dll does not support extensions higher than v1.1.
//
// Note: These externals should be declared in DllMain.cpp and set in ArnInitGlExtFunctions()
//
#ifdef WIN32
extern ARAN_API PFNGLMULTTRANSPOSEMATRIXFPROC			glMultTransposeMatrixf;

extern ARAN_API PFNGLGENBUFFERSARBPROC					glGenBuffersARB;
extern ARAN_API PFNGLBINDBUFFERARBPROC					glBindBufferARB;
extern ARAN_API PFNGLBUFFERDATAARBPROC					glBufferDataARB;
extern ARAN_API PFNGLBUFFERSUBDATAARBPROC				glBufferSubDataARB;
extern ARAN_API PFNGLDELETEBUFFERSARBPROC				glDeleteBuffersARB;
extern ARAN_API PFNGLGETBUFFERPARAMETERIVARBPROC			glGetBufferParameterivARB;
extern ARAN_API PFNGLMAPBUFFERARBPROC					glMapBufferARB;
extern ARAN_API PFNGLUNMAPBUFFERARBPROC					glUnmapBufferARB;

extern ARAN_API PFNGLACTIVETEXTUREARBPROC				glActiveTextureARB;
extern ARAN_API PFNGLCLIENTACTIVETEXTUREARBPROC			glClientActiveTextureARB;
extern ARAN_API PFNGLMULTITEXCOORD1DARBPROC				glMultiTexCoord1dARB;
extern ARAN_API PFNGLMULTITEXCOORD1DVARBPROC				glMultiTexCoord1dvARB;
extern ARAN_API PFNGLMULTITEXCOORD1FARBPROC				glMultiTexCoord1fARB;
extern ARAN_API PFNGLMULTITEXCOORD1FVARBPROC				glMultiTexCoord1fvARB;
extern ARAN_API PFNGLMULTITEXCOORD1IARBPROC				glMultiTexCoord1iARB;
extern ARAN_API PFNGLMULTITEXCOORD1IVARBPROC				glMultiTexCoord1ivARB;
extern ARAN_API PFNGLMULTITEXCOORD1SARBPROC				glMultiTexCoord1sARB;
extern ARAN_API PFNGLMULTITEXCOORD1SVARBPROC				glMultiTexCoord1svARB;
extern ARAN_API PFNGLMULTITEXCOORD2DARBPROC				glMultiTexCoord2dARB;
extern ARAN_API PFNGLMULTITEXCOORD2DVARBPROC				glMultiTexCoord2dvARB;
extern ARAN_API PFNGLMULTITEXCOORD2FARBPROC				glMultiTexCoord2fARB;
extern ARAN_API PFNGLMULTITEXCOORD2FVARBPROC				glMultiTexCoord2fvARB;
extern ARAN_API PFNGLMULTITEXCOORD2IARBPROC				glMultiTexCoord2iARB;
extern ARAN_API PFNGLMULTITEXCOORD2IVARBPROC				glMultiTexCoord2ivARB;
extern ARAN_API PFNGLMULTITEXCOORD2SARBPROC				glMultiTexCoord2sARB;
extern ARAN_API PFNGLMULTITEXCOORD2SVARBPROC				glMultiTexCoord2svARB;
extern ARAN_API PFNGLMULTITEXCOORD3DARBPROC				glMultiTexCoord3dARB;
extern ARAN_API PFNGLMULTITEXCOORD3DVARBPROC				glMultiTexCoord3dvARB;
extern ARAN_API PFNGLMULTITEXCOORD3FARBPROC				glMultiTexCoord3fARB;
extern ARAN_API PFNGLMULTITEXCOORD3FVARBPROC				glMultiTexCoord3fvARB;
extern ARAN_API PFNGLMULTITEXCOORD3IARBPROC				glMultiTexCoord3iARB;
extern ARAN_API PFNGLMULTITEXCOORD3IVARBPROC				glMultiTexCoord3ivARB;
extern ARAN_API PFNGLMULTITEXCOORD3SARBPROC				glMultiTexCoord3sARB;
extern ARAN_API PFNGLMULTITEXCOORD3SVARBPROC				glMultiTexCoord3svARB;
extern ARAN_API PFNGLMULTITEXCOORD4DARBPROC				glMultiTexCoord4dARB;
extern ARAN_API PFNGLMULTITEXCOORD4DVARBPROC				glMultiTexCoord4dvARB;
extern ARAN_API PFNGLMULTITEXCOORD4FARBPROC				glMultiTexCoord4fARB;
extern ARAN_API PFNGLMULTITEXCOORD4FVARBPROC				glMultiTexCoord4fvARB;
extern ARAN_API PFNGLMULTITEXCOORD4IARBPROC				glMultiTexCoord4iARB;
extern ARAN_API PFNGLMULTITEXCOORD4IVARBPROC				glMultiTexCoord4ivARB;
extern ARAN_API PFNGLMULTITEXCOORD4SARBPROC				glMultiTexCoord4sARB;
extern ARAN_API PFNGLMULTITEXCOORD4SVARBPROC				glMultiTexCoord4svARB;

#endif

ARAN_API void ArnInitGlExtFunctions();
