#include "AranPCH.h"
#include "ArnXmlString.h"

IMPLEMENT_SINGLETON(ArnXmlString)

#define TAG_INIT(x) TAG_##x(xercesc::XMLString::transcode(#x), XMLStringDeleter())
#define ATTR_INIT(x) ATTR_##x(xercesc::XMLString::transcode(#x), XMLStringDeleter())
#define VAL_INIT(x) VAL_##x(xercesc::XMLString::transcode(#x), XMLStringDeleter())

ArnXmlString::ArnXmlString()
: TAG_INIT(object)
, TAG_INIT(scene)
, TAG_INIT(transform)
, TAG_INIT(scaling)
, TAG_INIT(rotation)
, TAG_INIT(translation)
, TAG_INIT(chunk)
, TAG_INIT(template)
, TAG_INIT(int)
, TAG_INIT(int4)
, TAG_INIT(float)
, TAG_INIT(float2)
, TAG_INIT(float3)
, TAG_INIT(arraydata)
, TAG_INIT(data)
, TAG_INIT(skeleton)
, TAG_INIT(bone)
, TAG_INIT(head)
, TAG_INIT(tail)
, TAG_INIT(roll)
, TAG_INIT(mesh)
, TAG_INIT(vertex)
, TAG_INIT(face)
, TAG_INIT(uv)
, TAG_INIT(vertexgroup)
, TAG_INIT(material)
, TAG_INIT(light)
, TAG_INIT(camera)
, TAG_INIT(diffuse)
, TAG_INIT(ambient)
, TAG_INIT(specular)
, TAG_INIT(emissive)
, TAG_INIT(power)
, TAG_INIT(texture)
, TAG_INIT(facegroup)
, TAG_INIT(field)
, TAG_INIT(ipo)
, TAG_INIT(curve)
, TAG_INIT(controlpoint)
, TAG_INIT(action)
, TAG_INIT(actionstrip)
, TAG_INIT(objectipomap)
////////////////////////////////////////////////////////////
, ATTR_INIT(name)
, ATTR_INIT(type)
, ATTR_INIT(place)
, ATTR_INIT(unit)
, ATTR_INIT(rtclass)
, ATTR_INIT(startoffset)
, ATTR_INIT(endoffset)
, ATTR_INIT(farclip)
, ATTR_INIT(nearclip)
, ATTR_INIT(fovdeg)
, ATTR_INIT(value)
, ATTR_INIT(path)
, ATTR_INIT(mtrl)
, ATTR_INIT(usage)
, ATTR_INIT(x)
, ATTR_INIT(y)
, ATTR_INIT(z)
, ATTR_INIT(w)
, ATTR_INIT(r)
, ATTR_INIT(g)
, ATTR_INIT(b)
, ATTR_INIT(a)
, ATTR_INIT(ipo)
, ATTR_INIT(obj)
, ATTR_INIT(shadeless)
////////////////////////////////////////////////////////////
, VAL_INIT(ArnSceneGraph)
, VAL_INIT(ArnMesh)
, VAL_INIT(ArnLight)
, VAL_INIT(ArnCamera)
, VAL_INIT(ArnMaterial)
, VAL_INIT(ArnSkeleton)
, VAL_INIT(ArnIpo)
, VAL_INIT(ArnAction)
, VAL_INIT(ArnBone)

, VAL_INIT(xml)
, VAL_INIT(bin)

, VAL_INIT(srt)
, VAL_INIT(matrix)

, VAL_INIT(euler)
, VAL_INIT(quat)

, VAL_INIT(deg)
, VAL_INIT(rad)

, VAL_INIT(point)
, VAL_INIT(spot)
, VAL_INIT(directional)

, VAL_INIT(image)

, VAL_INIT(persp)
, VAL_INIT(ortho)
{
}

ArnXmlString::~ArnXmlString()
{
}
