// ArnGlExtEntry.h
// 2009 Geoyeob Kim
//
// To reduce repetition of code, we will include this code snippet
// to the several places by redefine the macro ARNGL_EXT_ENTRY(type, val)
// for every time they are used.
//
// Note that this snippet can be included one or more times to the same
// source code, we should not use #pragma once or include once macros.
//

ARN_GL_EXT_ENTRY(PFNGLMULTTRANSPOSEMATRIXFPROC, glMultTransposeMatrixf);

ARN_GL_EXT_ENTRY(PFNGLGENBUFFERSARBPROC, glGenBuffersARB);
ARN_GL_EXT_ENTRY(PFNGLBINDBUFFERARBPROC, glBindBufferARB);
ARN_GL_EXT_ENTRY(PFNGLBUFFERDATAARBPROC, glBufferDataARB);
ARN_GL_EXT_ENTRY(PFNGLBUFFERSUBDATAARBPROC, glBufferSubDataARB);
ARN_GL_EXT_ENTRY(PFNGLDELETEBUFFERSARBPROC, glDeleteBuffersARB);
ARN_GL_EXT_ENTRY(PFNGLGETBUFFERPARAMETERIVARBPROC, glGetBufferParameterivARB);
ARN_GL_EXT_ENTRY(PFNGLMAPBUFFERARBPROC, glMapBufferARB);
ARN_GL_EXT_ENTRY(PFNGLUNMAPBUFFERARBPROC, glUnmapBufferARB);

ARN_GL_EXT_ENTRY(PFNGLACTIVETEXTUREARBPROC, glActiveTextureARB);
ARN_GL_EXT_ENTRY(PFNGLCLIENTACTIVETEXTUREARBPROC, glClientActiveTextureARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1DARBPROC, glMultiTexCoord1dARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1DVARBPROC, glMultiTexCoord1dvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1FARBPROC, glMultiTexCoord1fARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1FVARBPROC, glMultiTexCoord1fvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1IARBPROC, glMultiTexCoord1iARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1IVARBPROC, glMultiTexCoord1ivARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1SARBPROC, glMultiTexCoord1sARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD1SVARBPROC, glMultiTexCoord1svARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2DARBPROC, glMultiTexCoord2dARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2DVARBPROC, glMultiTexCoord2dvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2FARBPROC, glMultiTexCoord2fARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2FVARBPROC, glMultiTexCoord2fvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2IARBPROC, glMultiTexCoord2iARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2IVARBPROC, glMultiTexCoord2ivARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2SARBPROC, glMultiTexCoord2sARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD2SVARBPROC, glMultiTexCoord2svARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3DARBPROC, glMultiTexCoord3dARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3DVARBPROC, glMultiTexCoord3dvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3FARBPROC, glMultiTexCoord3fARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3FVARBPROC, glMultiTexCoord3fvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3IARBPROC, glMultiTexCoord3iARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3IVARBPROC, glMultiTexCoord3ivARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3SARBPROC, glMultiTexCoord3sARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD3SVARBPROC, glMultiTexCoord3svARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4DARBPROC, glMultiTexCoord4dARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4DVARBPROC, glMultiTexCoord4dvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4FARBPROC, glMultiTexCoord4fARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4FVARBPROC, glMultiTexCoord4fvARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4IARBPROC, glMultiTexCoord4iARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4IVARBPROC, glMultiTexCoord4ivARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4SARBPROC, glMultiTexCoord4sARB);
ARN_GL_EXT_ENTRY(PFNGLMULTITEXCOORD4SVARBPROC, glMultiTexCoord4svARB);
